version=96 # bonk version
[f.f0]
0=game
1=Skin
2=Peer
3=b2Vec2
4=b2BodyDef
5=Map
6=Maps
7=Game
8=QuickMaps
9=b2Body
10=b2FixtureDef
12=b2World
14=b2PolygonShape
15=b2CircleShape
17=b2Math
18=b2RevoluteJointDef
20=b2PrismaticJointDef
23=b2DistanceJointDef
24=b2GearJointDef
25=b2AABB
26=BonkView
27=Controls
28=PeerClass
29=GameRenderer
30=Map2
31=BonkObject
32=Shape
33=Spawn
34=CaptureZone
35=FootballWall
36=Ball
37=FootballPlayer
38=GameCountdown
39=BodyGraphics
40=MapRenderer
41=RoundGraphics
42=Player
43=GameMessages
44=PlayerRenderer
45=Arrow
46=SnowRenderer
47=AvatarManager
48=FPS
args=peerjs,socketio,box2d
[f.f1]
0=editSkin
1=editSkinLayer
2=skinRenderer
3=isSkinColorChanged
4=skinColorTeam
14=layerNames
15=colorPicker
21=layerSliderEvent
22=layerSliderTimeout
39=skinOffsetX
40=skinOffsetY
43=skinEventCallbacks
44=skinLayerSelectWindow
name=SkinManager
[f.f2]
name=skinLayerZoom
args=e
[f.f3]
name=getLayerName
args=i
[f.f4]
name=layerSliderTickHandle
args=e
[f.f6]
0=layer
name=loadShape
[f.f7]
name=setShortSliderTimeout
[f.f8]
0=e
name=layerSliderHandler
[f.f9]
1=htmlCode
name=setSkinBackground
args=color
[f.f10]
0=prevLayer
name=moveLayerUp
[f.f11]
name=redrawLayer
[f.f12]
name=changeLayerColor
args=color
[f.f13]
name=showSkinBackgroundColorPicker
[f.f14]
4=htmlCode
name=openLayerProperties
[f.f15]
name=boolToString
args=bool
[f.f16]
0=val
name=changeLayerProperty
args=e
[f.f18]
args=skin
[f.f21]
args=eventName,callback
[f.f22]
0=eventName
name=dispatchSkinEvent
[f.f23]
name=selectLayer
[f.f24]
name=hideTeamColorDropdown
[f.f25]
name=flipLayer
args=layer
[f.f26]
name=setCursorGrab
[f.f27]
1=x
3=y
name=setLayerXY
args=e
[f.f28]
name=round
args=number
[f.f29]
0=closeButton
2=layerImage
3=unused
name=openSkinLayerSelectWindow
[f.f30]
name=removeLayer
[f.f31]
name=hideLayerSelect
[f.f32]
name=setSkinTeam
args=e
[f.f33]
0=string
1=padLength
name=hexToString
args=hex
[f.f34]
1=row
2=cell
3=layerName
4=layerPreview
5=layerPreviewImage
6=unused
name=setLayerNames
[f.f35]
0=nextLayer
name=moveLayerDown
[f.f36]
0=layerColor
name=highlightLayer
[f.f37]
name=redrawIfNeeded
[f.f38]
name=removeCursorGrab
[f.f39]
3=htmlCode
name=setColorFieldBackground
[f.f40]
name=grabLayer
args=e
[f.f42]
name=teamColorDropdown
args=e
[f.f43]
name=ThumbMaker
0=thumbElement
[f.f44]
name=IngameManager
args=info,token
0=self
1=currentId
2=playerList
3=currentToken
4=lobby
12=room
13=gameWorld
26=gameWorld_
31=gameSessionEvents
[f.f45]
name=setUsername
args=id,username
[f.f46]
name=hostMapSuggestHandler
args=map,playerId
0=deleteThis
1=unused
[f.f54]
name=readyResetHandler
0=i
[f.f55]
name=playerJoinHandler
args=id,username,guest,level,team,skinObj
0=skin
1=playerCount
2=i
[f.f56]
name=passwordChangeHandler
args=hasPassword
[f.f57]
name=tabbedHandler
args=playerId,tabbed
[f.f58]
name=unfavoriteMap
[f.f60]
name=mapAddHandler
args=map
[f.f61]
name=p2pRevertHandler
args=stepGroup,step
[f.f62]
name=curateReset
[f.f63]
name=hostLeaveHandler
args=oldHostId,newHostId,leaveStep
0=oldHostUsername
1=oldHost
[f.f64]
name=commandHandler
0=commandSplit
1=_argument
2=argument
3=startsWithQuote
4=endsWithQuote
6=commandPart
7=firstChar
8=lastChar
[f.f65]
name=readyHandler
args=playerId,isReady
[f.f66]
name=friendHandler
args=playerId
[f.f67]
name=teamLockHandler
args=isLocked
[f.f68]
name=mapDeleteHandler
[f.f69]
name=nerfBuffHandler
args=playerId,balance
[f.f70]
name=serverMessageHandler
args=message
[f.f71]
name=gameStartHandler
[f.f72]
name=_startGame
[f.f73]
name=curateHandler
args=success,reason
[f.f74]
name=mapSuggestHandler
args=mapName,mapAuthor,playerId
[f.f75]
name=setXPProgress
args=percent,hasAnimation
0=XPAnimation
[f.f76]
name=playerLeaveHandler
args=playerId,leaveStep
[f.f77]
name=teamToggleHandler
args=hasTeams
0=i
[f.f78]
name=XPGainHandler
args=newXP
[f.f79]
name=disconnectHandler
[f.f80]
name=leaveConfirm
0=playerAmount
[f.f81]
name=showConfirmNoHost
[f.f82]
name=confirmNoHost
[f.f83]
name=confirm
[f.f84]
name=_cancel
[f.f85]
name=endRoom
[f.f86]
name=showConfirm
[f.f87]
name=cancel
[f.f89]
name=cancelNoHost
[f.f91]
name=_cancelNoHost
[f.f92]
name=fillXPBar
args=hasAnimation
0=currentLevel
1=currentLevelXP
2=nextLevelXP
3=totalXPNeeded
5=currentProgress
6=nextProgress
7=XPAnimation
[f.f93]
name=physicsChangeHandler
args=mode,physics
[f.f94]
name=gameEnd
[f.f95]
name=showGameHandler
args=gameState
0=inputs
1=i
2=inputStep
3=inputId
4=decodedInputs
5=i
[f.f96]
name=gameEndHandler
[f.f97]
name=gameCompleteHandler
[f.f98]
name=unmuteHandler
args=playerId
[f.f99]
name=lobbyMapHandler
[f.f100]
name=teamChangeHandler
args=playerId,team
[f.f101]
name=startGame
1=i
[f.f102]
name=displayStatus
[f.f103]
name=afkWarnHandler
[f.f104]
name=sessionEvent
0=evName
1=i
[f.f105]
name=recordResponseHandler
[f.f106]
name=showLobbyHandler
[f.f108]
name=levelUpHandler
[f.f109]
name=favoriteMap
[f.f111]
name=nameChangeHandler
[f.f112]
name=pingDataHandler
[f.f113]
name=debugWinnerHandler
[f.f115]
name=hostChangeHandler
[f.f116]
name=localRevertHandler
[f.f117]
name=muteHandler
[f.f118]
name=kickBanHandler
[f.f119]
name=roomCreateHandler
[f.f120]
name=roomJoinHandler
[f.f121]
name=modeChangeHandler
args=mode
[f.f122]
name=winAmountChangeHandler
args=winAmount
[f.f124]
name=mapReorderHandler
[f.f126]
name=typingHandler
[f.f129]
name=newTokenHandler
args=token
[f.f132]
name=chatMessageHandler
args=playerId,message
0=username
[f.f133]
32=currentToken
name=RoomList
[f.f155]
args=token
[f.f184]
1=discs
163=newMap
args=map,playerInputs,playerActions,stepDuration,data,numPasses,isTutorial,quickMaps
[f.f216]
0=intLength
1=byte1
2=byte2
3=byte3
4=byte4
5=value
[f.f232]
0=randomColorIndex
args=colorSet
[f.f233]
1=layer
[f.f234]
args=obj
[f.f235]
0=view
2=layer
3=string
4=encodedString
[f.f236]
0=parseLayer
1=decodedString
2=view
5=unused
6=unused
7=unused
8=unused
9=hasBgColor
10=unused
11=_skinLayers
12=skinLayers
13=version
14=layerId
15=_layerId
16=a
17=b
args=string
[f.f237]
0=__version
1=layer
2=_version
3=version2
args=view
[f.f239]
0=controls
[f.f241]
0=controls
1=version
2=oldQuality
args=string
[f.f242]
args=id
[f.f246]
args=map
[f.f249]
name=ReplayRenderer
0=self
2=replays
3=replayIndex
4=hasReplays
5=currentReplay
6=replayStartingState
7=roundCount
8=inputs
9=replayAdminInputs
10=replayPlayerArray
11=steps
12=renderer
13=gameSettings
14=currentStep
15=replayStartTime
16=maxReplayOffset
17=replayOffset
18=isFetchingReplays
19=replayId
20=shouldGetReplayId
24=timeSinceLastFrame
25=remainingTime
28=replayPauseTime
29=physics
31=replayEvents
[f.f250]
name=loadReplay
0=playerIndex
1=currentPlayerSkin
[f.f251]
name=fetchReplays
0=replayFetchPayload
[f.f252]
0=i
1=replayMap
2=j
3=playerCount
4=j
args=response
[f.f254]
name=fadeInMenu
[f.f255]
name=getInputs
args=step
0=inputList
1=i
2=j
[f.f256]
name=fadeOutMenu
[f.f257]
name=replayFrameAdvance
0=currentTime
1=deltaTime
3=stepLength
4=stepLengthAdjusted
5=deleteThis
6=deleteThis
7=shakeX
8=shakeY
9=shakeDistance
10=remainder
[f.f260]
name=replayEvent
; args=eventArgs
0=eventName
1=i
[f.f261]
args=eventName,callback
[f.f265]
0=timeSincePause
[f.f267]
name=performStep
args=stepLength
0=currentInputs
1=nextStepState
[f.f271]
name=countFPS
[f.f306]
10=joint
[f.f325]
name=SkinRenderer
[f.f361]
name=NetworkEngine
1=self
3=connection
9=server
21=host
28=url
33=self
36=tSync
37=connection
91=peer
93=peers
134=joinURL
[f.f363]
name=synchronize
[f.f369]
name=networkEvent
[f.f374]
name=connectToPeer
args=id
[f.f406]
name=establishPeer
args=peer
[f.f499]
args=prevStep,currentStep,t,gameSettings,inputs,stepIndex
0=needsResize
1=i
3=i
4=i
5=i
6=i
7=playerId
8=playerTeam
9=isDeathArrows
10=i
11=shake
[f.f500]
0=shake
[f.f501]
0=scale
1=bgCanvas
[f.f502]
name=makeGradient
args=color1,color2
0=ctx
1=gradient
[f.f513]
args=prevStep,currentStep,t
0=i
[f.f522]
name=InputHandler
[f.f554]
args=skin1,skin2
[f.f563]
0=mainMenu
11=connection
19=token
95=news
115=isLoading
name=MainMenu
[f.f564]
name=tabOut
[f.f618]
name=tabIn
[f.f660]
name=showHint
[f.f661]
name=unfriend
[f.f663]
args=fastOrSlow
[f.f664]
name=saveControls
[f.f677]
name=animateGuestOrAccountScreen
[f.f669]
args=roomInfo
[f.f731]
0=row
1=cell
3=request
4=row
5=nameCell
6=unfriendCell
7=unfriendButton
8=acceptCell
9=acceptButton
10=areFriendsOnline
11=areFriendsOffline
13=friend
14=table
15=row
16=nameCell
17=unfriendCell
18=unfriendButton
19=onlineCell
20=joinButton
21=row
22=cell
23=row
24=cell
name=openFriendList
args=e
[f.f735]
0=mode
1=game
name=createQuickGame
[f.f766]
name=GraphicsHandler
[f.f743]
name=tutorialText
[f.f762]
name=CapSoundHandler
[f.f816]
name=checkIfHidden
[f.f817]
name=MapLoadWindow
[f.f785]
8=ppm
[f.f903]
name=Lobby
[f.f890]
name=SkinManagerElementHandler
[f.f902]
name=sendLogInChat
[f.f951]
args=mapName,mapAuthor,playerId
0=messageEl
1=username
6=newScroll
7=userNameContainer
8=text1Container
9=mapNameContainer
10=text2Container
11=mapAuthorContainer
[f.f1002]
name=EnterFrameDispatcher
[f.f1006]
name=ContainerSkinRenderer
[f.f1001]
name=getPageWidth
[f.f1015]
name=ColorPicker
[f.f1035]
15=world
97=editorHelp
name=MapEditor
[f.f1226]
args=e
[f.f1256]
args=button
[f.f1257]
2=rads
4=latDistance
5=longDistance
10=v1
13=v2
14=multipliedByRadius
args=lat1,long1,lat2,long2,useMiles
[f.f1258]
0=firstByte
1=secondByte
2=thirdByte
[f.f1259]
0=currentTime
2=expireString
args=name,value,daysToExpire
[f.f1260]
name=getPageHeight
[f.f1263]
name=CanvasHandler
[f.f1279]
name=LobbyHandler
[f.f1343]
0=regex
args=string,from,to
[f.f1344]
1=replacement
3=badWord
4=badWordPos
6=endIndex
args=string,badWordList
[f.f1345]
0=badWordList
1=foundBadWord
args=string
[f.f1346]
0=preCensor
1=postCensor
args=string,startIndex,endIndex
[f.f1349]
args=on
[f.f1350]
0=mainMenu
1=deleteThis
2=unused
[f.ef0]
name=MapParser
[f.ef1]
name=AvatarRenderer
[f.ef2]
name=FootballPhysics
[f.ef3]
name=Physics